### PR TITLE
PuppetConf 2016 DSC Demos

### PR DESCRIPTION
**Pull request by Iristyle**
Initial manifest dump.. need to run locally to verify, but most of these were lifted from previously working demos I've done.

### CODE REVIEW

**Comment by Iristyle** [comment]
All updated / tested against puppet agent 1.7.0 / DSC module 1.1.0 and Windows 2012R2.

Will have to think about some more failure scenarios for reporting purposes... maybe @jpogran has some good ideas there.

**Comment by ccaum** [comment]
Nice. Is this ready to merge or do you want to wait to work through failure scenarios?

**Comment by ccaum** [comment]
@Iristyle Looks like this has conflicts now :-/

**Comment by Iristyle** [comment]
@ccaum that's because Glenn merged it (in a slightly roundabout way) - it's on prod branch now - https://github.com/puppetlabs/pmm-puppet-site/commits/production

**Pull request closed without merging**
